defaults:
    - override hydra/launcher: local
    - override hydra/output: local

env_name: FrankaBinPick-v0
mode: evaluation
seed: 0
render: none
camera_name: None
output_dir: /checkpoint/plancaster/outputs/robohive_base/demonstrations/franka-FrankaBinPick
output_name: demo
num_rollouts: 1000
sparse_reward: True
policy_path: robohive.envs.arms.bin_pick_v0.BinPickPolicy

# hydra
hydra:
    job:
        name: collect_demos
    launcher:
        cpus_per_task: 8
        gpus_per_node: 1
        tasks_per_node: 1
        timeout_min: 1200
        mem_gb: 80
        name: ${hydra.job.name}
        submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    sweep:
        dir: /checkpoint/${oc.env:USER}/outputs